dist: trusty
cache:
  directories:
  - $HOME/.isabelle
  - $HOME/.opam
sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install libgmp3-dev
# - git clone https://github.com/polyml/polyml.git
# - cd polyml
# - git checkout v5.6
# - ./configure
# - make
# - make compiler
# - sudo make install
# - cd -
# - sudo updatedb
# - locate libpolymain.a
- wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sudo sh -s /usr/local/bin
- export OPAMJOBS=2
- opam init -y --comp=4.04.1
- eval `opam config env`
- opam update
- opam install -y ocamlbuild ocamlfind batteries yojson bignum easy-format bisect_ppx zarith depext sha
- git clone https://github.com/mrsmkl/ECC-OCaml.git ECC-OCaml
- cd ECC-OCaml/src
- make depend
- make
- make install || echo "fails the second time and on"
- cd ../..
- git clone https://bitbucket.org/Peter_Sewell/lem.git lemdir
- cd lemdir
- make || echo "failure expected"
- cd ..
- export PATH=./lemdir:$PATH
- wget https://isabelle.in.tum.de/dist/Isabelle2016-1_app.tar.gz
- tar xf Isabelle2016-1_app.tar.gz
- export PATH=./Isabelle2016-1/bin:$PATH
# - git clone git://github.com/HOL-Theorem-Prover/HOL.git
# - cd HOL
# - echo 'val polymllibdir = "/usr/local/lib"' > tools-poly/poly-includes.ML
# - poly < tools/smart-configure.sml
# - bin/build -j 2
# - cd -
script:
- make lem-ocaml
- make lem-thy
- make lem-hol
- make lem-coq
# - cd lem
# - ../HOL/bin/Holmake evmTheory.uo
# - cd -
- cd tester
- sh compile.sh
- ./runVmTest.native 89
- cd -
- make light-isabelle
